#!/bin/bash
# Author: rbost@redhat.com (2020)

VERSION="0.0.2"

if [[ -n ${ZSH_VERSION} ]] && [[ ! -z ${ZSH_VERSION} ]]; then
  INDEX_START=1
  INDEX_OFFSET=0
elif [[ -n $BASH_VERSION ]]; then
  INDEX_START=0
  INDEX_OFFSET=1
else
  echo "  unknown"
fi

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

usage() { 
    echo -e "Login to OpenShift 4 cluster using installation assets directory.\n"
    echo -e "Usage: oc flogin -p PATH [-h|-v|-D <depth>]"
    echo -e "  -p: Set the search PATH"
    echo -e "  -v: Display the version"
    echo -e "  -h: Display this help"
    echo -e "  -D: Set the MAX_DEPTH used by the find command"
    echo -e "Example:\n  $ oc flogin -p ~/installations/"
    echo -e "  $ oc flogin -v"
    echo -e "  $ oc flogin -h"
    exit 1
}

if [ $# -eq 0 ];
then
    echo -e "\n${RED}Error: Missing path.${NC}\n"
    usage
else
    while getopts "vhD:p:" OPT
    do
      case $OPT in
        v)
          echo $VERSION && exit 0
          ;;
        D)
          MAX_DEPTH=${OPTARG}
          ;;
        p)
          if [[ ! -d ${OPTARG} ]]
          then
            echo "\n${RED}Error: Invalid path '${OPTARG}'.${NC}\n"
            usage
          else
            KUBE_PATH=$OPTARG
          fi
          ;;
        h|help|?|*)
          usage
          ;;
      esac
    done
fi

MAX_DEPTH=${MAX_DEPTH:-5}

# Create the Array of available KUBECONFIG
KUBECONFIG_LIST=($(find ${KUBE_PATH} -maxdepth ${MAX_DEPTH} -type f -name kubeconfig))

# Display choices & select desired kubeconfig
length=${#KUBECONFIG_LIST[@]}
if [[ ${length} == 1 ]]
then
    KUBEINDEX=$INDEX_START
else
  if [[ ${length} -gt 1 ]]
  then
    echo "Multiple kubeconfig file found. Please select one from the list"
    if [[ -z $ZSH_VERSION ]]; then
      for index in "${!KUBECONFIG_LIST[@]}"; do
        printf '[%s] %s\n' "$index" "${KUBECONFIG_LIST[index]}"
      done
      echo
      read -p "Please select the kubeconfig file: " KUBEINDEX
    else
      for index in $(seq 1 ${length}); do
        printf '[%s] %s\n' "$index" "${KUBECONFIG_LIST[index]}"
      done
      echo
      read "KUBEINDEX?Please select the kubeconfig file: "
    fi
  else
    echo -e "${RED}No kubeconfig file found in given path: ${KUBE_PATH}${NC}"
    exit 5
  fi
fi

kubeconfig=${KUBECONFIG_LIST[KUBEINDEX]}
kubeadminpassword="$(dirname ${KUBECONFIG_LIST[KUBEINDEX]})/kubeadmin-password"
server=$(grep -m1 'server: ' $kubeconfig | awk '{print $2}')

if [[ -f ${kubeadminpassword} ]]
then
    kpass=$(cat ${kubeadminpassword})
    echo -e "${GREEN}Login with user/password from $kubeconfig${NC}"
    oc login -u kubeadmin --insecure-skip-tls-verify=true  -p ${kpass} ${server}
else
    echo -e "${RED}No kubeadmin-password file found in given path: ${KUBE_PATH}${NC}"
    if [[ "$_" != "$0" ]]
    then
      echo -e "${GREEN}Setting KUBECONFIG variable as 'export KUBECONFIG=${kubeconfig}'${NC}"
      export KUBECONFIG=${kubeconfig}
    else
      echo -e "${GREEN}Please consider to Source the script by running the command: '. $*'${NC}"
      echo -e "${GREEN}Or exporting the variable: 'export KUBECONFIG=${kubeconfig}'${NC}"
    fi
fi
